name: SpringBootBuild

on:
  pull_request :
    branches : [ main ]
  push :
    branches : [ main ]

jobs:
  build:
    runs-on : ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.0

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Build with Gradle
        run : ./gradlew build -x test

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: SpringBootAPI.war
          path: build/libs/api-0.0.1-SNAPSHOT.war

